### ISSUE TITLE
Should remove ConfigureDataProtection (make it overload of AddDataProtection)

### ISSUE THREAD

**Issue by HaoK** [aspnet/DataProtection#100]

**Comment by muratg** [comment]
Looking at these two methods, this kind of makes sense to me.  @GrabYourPitchforks What do you think?

**Comment by GrabYourPitchforks** [comment]
I'm impartial. Just follow whatever pattern is already established by the other framework components. Also make sure that you don't regress the ability for the developer to configure the system if a separate component calls Add on his behalf.

**Comment by HaoK** [comment]
0b808ca75a54ee83f2b5aca5a077dcb47544fbe9
