### ISSUE TITLE
Storing data protection keys file in another storage systems

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/DataProtection#104]
> From https://twitter.com/PinpointTownes/status/665165343879491585

Is there any samples to store the data protection keys file in another storage systems like Azure vault, azure storage, AWS S3, etc.?

**Comment by tugberkugurlu** [comment]
I can see that there is already an issue for this: https://github.com/aspnet/DataProtection/issues/92

**Comment by blowdart** [comment]
Closed as dupe of #92
