### ISSUE TITLE
Another way of DataProtectionProvider?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/DataProtection#115]
_From @yuezhongxin on January 18, 2016 3:55_

Startup.cs code:

```cs
var dataProtection = new Microsoft.AspNet.DataProtection.DataProtectionProvider(new DirectoryInfo(@"\\10.10.10.10\shared-auth-ticket-keys\"));

app.UseCookieAuthentication((cookieOptions) =>
{
    cookieOptions.AutomaticAuthenticate = true;
    cookieOptions.AutomaticChallenge = true;
    cookieOptions.CookieHttpOnly = true;
    cookieOptions.ExpireTimeSpan = TimeSpan.FromMinutes(43200);
    cookieOptions.LoginPath = new PathString("/account/login");
    cookieOptions.CookieName = ".CNBlogsAdCookie";
    cookieOptions.CookiePath = "/";
    cookieOptions.DataProtectionProvider = dataProtection;
});
```

Web application publishing in multiple servers, I use the following method(#624):

> You need to create an UNC share somewhere that both applications can access, and use that, for example \keystore\keystore

But I do not want to use this sharing, there is no other solution? For example, using SQL Server reads the key.

_Copied from original issue: aspnet/Security#659_

**Comment by GuardRex** [comment]
@yuezhongxin You can setup a custom `IXmlRepository` ... more on that here: https://github.com/aspnet/DataProtection/issues/92

The team is recommending encryption using the "certificate method" where a certificate is put on each web server, see https://docs.asp.net/en/latest/security/data-protection/implementation/key-encryption-at-rest.html#certificate-based-encryption-with-windows-dpapi-ng. I took the vastly more dangerous approach of rolling my own `IXmlEncryptor` to avoid having to put a cert on all of my servers.

**Comment by yuezhongxin** [comment]
@GuardRex Thank you very much, but the more information you say, I need to take the time to learn.👻

**Comment by GuardRex** [comment]
@yuezhongxin np ... also checkout @GrabYourPitchforks note on SQL Server's built-in transparent data encryption in https://github.com/aspnet/DataProtection/issues/99#issuecomment-153429786.

**Comment by yuezhongxin** [comment]
@GuardRex I read, but still do not understand, can you provide some sample code of reading keys from the SQL Server? Thank you.

**Comment by GuardRex** [comment]
@yuezhongxin I only have this code for Azure Table Storage.

You should replace the `.FetchAll()` above with a pull from your database ... just get the XML strings parsed into an `IList<XElement>` and take them from there.

On the saving keys side, you just need to replace that `.Insert()` method with one that will save the `element.ToString()` in your database.

The `CustomXmlRepository` class has to be registered in `project.json` ...
```json
services.AddSingleton<IXmlRepository, CustomXmlRepository>();
```

This doesn't encrypt the keys at rest. I use a custom algorithm, but the team doesn't recommend the approach that I'm using. See @GrabYourPitchforks comment about what to do: https://github.com/aspnet/DataProtection/issues/99#issuecomment-153429786

**Comment by yuezhongxin** [comment]
@GuardRex Well, I try next, thank you very much!

**Comment by yuezhongxin** [comment]
@blowdart Before you say: (aspnet/Security#624)

>You need to point the key directory to a shared directory which both applications can access. Putting it in c:\shared-auth-ticket-keys\ isn't enough in multiple server scenarios, as it's still going to create a key ring local to each machine.

>You need to create an UNC share somewhere that both applications can access, and use that, for example \keystore\keystore

>Or you implement a key store yourself suitable to your architecture, for example, using SQL Server.

Now I do not use UNC share, and take the following method:

```cs
public class CustomXmlRepository : IXmlRepository
{
    private readonly string keyContent =
@"<?xml version='1.0' encoding='utf-8'?>
<key id='c1cb059c-f0a6-4af9-be37-f71518aa9de7' version='1'>
<creationDate>2016-01-04T03:46:52.8139251Z</creationDate>
<activationDate>2016-01-04T03:46:52.8090684Z</activationDate>
<expirationDate>2016-04-03T03:46:52.8090684Z</expirationDate>
<descriptor deserializerType='Microsoft.AspNet.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'>
<descriptor>
<encryption algorithm='AES_256_CBC' />
<validation algorithm='HMACSHA256' />
<masterKey p4:requiresEncryption='true' xmlns:p4='http://schemas.asp.net/2015/03/dataProtection'>
<!-- Warning: the key below is in an unencrypted form. -->
<value>2qn9LoAfVgMLLWvksshhfsjwwemfdkffHVp8dVuNmHADFNvjdvHJQdfcUbwJatnfGWWu+gBnIQTj64py/JuP64L9g==</value>
</masterKey>
</descriptor>
</descriptor>
</key>";

    public virtual IReadOnlyCollection<XElement> GetAllElements()
    {
        return GetAllElementsCore().ToList().AsReadOnly();
    }

    private IEnumerable<XElement> GetAllElementsCore()
    {
        yield return XElement.Parse(keyContent);
    }
    public virtual void StoreElement(XElement element, string friendlyName)
    {
        if (element == null)
        {
            throw new ArgumentNullException(nameof(element));
        }
        StoreElementCore(element, friendlyName);
    }

    private void StoreElementCore(XElement element, string filename)
    {
    }
}
```

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IXmlRepository, CustomXmlRepository>();
}
```
Now have access to the same xml content, but still does not work on multiple servers.

**Comment by blowdart** [comment]
Did you set a common application name in code?

**Comment by yuezhongxin** [comment]
@blowdart Now the following error:

![qq20160121-0 2x](https://cloud.githubusercontent.com/assets/6800671/12481584/1f4c3b36-c085-11e5-9422-a19c17c6e298.png)

**Comment by blowdart** [comment]
And you added the Data Protection nuget package right? And included it in the using statement?

OK frankly this is too hard to diagnose from code snippets. Post a repo somewhere.

**Comment by yuezhongxin** [comment]
@blowdart Sorry, I did not clearly describe the problem, I modified the following code:

```cs
services.AddDataProtection(configure =>
{
    configure.SetApplicationName("CNBlogs.Ad.Web");
});
```

And the application is published to multiple servers, it works, thank you very much! 👻

Another problem is that if I use `new Microsoft.AspNet.DataProtection.DataProtectionProvider("c:\keys")` and set a common application name, it will also work?

**Comment by blowdart** [comment]
Yes, you need to both share a keyring and set a shared application name. We use application names to provide isolation even if you have a shared keyring (this stops key leakage in a hosted environment)

**Comment by yuezhongxin** [comment]
@blowdart Indeed, I did two tests, one of tests:

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection(configure =>
    {
        configure.SetApplicationName("CNBlogs.Ad.Web");
    });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    var dataProtection = new Microsoft.AspNet.DataProtection.DataProtectionProvider(new DirectoryInfo(@"C:\keys"));// no use UNC share

    app.UseCookieAuthentication((cookieOptions) =>
    {
        cookieOptions.AutomaticAuthenticate = true;
        cookieOptions.AutomaticChallenge = true;
        cookieOptions.CookieHttpOnly = true;
        cookieOptions.ExpireTimeSpan = TimeSpan.FromMinutes(43200);
        cookieOptions.LoginPath = new PathString("/account/login");
        cookieOptions.CookieName = ".CNBlogsAdCookie";
        cookieOptions.CookiePath = "/";
        cookieOptions.DataProtectionProvider = dataProtection;
    });
}
```

As a result, publishing to two servers, it is not working.

Another test:

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IXmlRepository, CustomFileXmlRepository>();
    services.AddDataProtection(configure =>
    {
        configure.SetApplicationName("CNBlogs.Ad.Web");
    });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseCookieAuthentication((cookieOptions) =>
    {
        cookieOptions.AutomaticAuthenticate = true;
        cookieOptions.AutomaticChallenge = true;
        cookieOptions.CookieHttpOnly = true;
        cookieOptions.ExpireTimeSpan = TimeSpan.FromMinutes(43200);
        cookieOptions.LoginPath = new PathString("/account/login");
        cookieOptions.CookieName = ".CNBlogsAdCookie";
        cookieOptions.CookiePath = "/";
    });
}

public class CustomFileXmlRepository : IXmlRepository
{
    private readonly string fileName = @"C:\keys\key.xml";

    public virtual IReadOnlyCollection<XElement> GetAllElements()
    {
        return GetAllElementsCore().ToList().AsReadOnly();
    }

    private IEnumerable<XElement> GetAllElementsCore()
    {
        yield return XElement.Load(fileName);
    }
    public virtual void StoreElement(XElement element, string friendlyName)
    {
        if (element == null)
        {
            throw new ArgumentNullException(nameof(element));
        }
        StoreElementCore(element, friendlyName);
    }

    private void StoreElementCore(XElement element, string filename)
    {
    }
}
```

As a result, publishing to two servers, it works.

**Comment by blowdart** [comment]
I'm glad it's all working now. Now you just need to write your own shared keyring for SQL :)

**Comment by yuezhongxin** [comment]
@blowdart Yes, but it need some time, very very very grateful for your help.

**Comment by yuezhongxin** [comment]
@blowdart Then add a test:

```cs
public void ConfigureServices(IServiceCollection services)
{
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    // no use UNC share
    var dataProtection = new Microsoft.AspNet.DataProtection.DataProtectionProvider(new DirectoryInfo(@"C:\keys"),
    configure =>
    {
          configure.SetApplicationName("CNBlogs.Ad.Web");
    });

    app.UseCookieAuthentication((cookieOptions) =>
    {
        cookieOptions.AutomaticAuthenticate = true;
        cookieOptions.AutomaticChallenge = true;
        cookieOptions.CookieHttpOnly = true;
        cookieOptions.ExpireTimeSpan = TimeSpan.FromMinutes(43200);
        cookieOptions.LoginPath = new PathString("/account/login");
        cookieOptions.CookieName = ".CNBlogsAdCookie";
        cookieOptions.CookiePath = "/";
        cookieOptions.DataProtectionProvider = dataProtection;
    });
}
```

As a result, publishing to two servers, it works.

**Comment by blowdart** [comment]
Cool, I'll close the issue then :)
