### ISSUE TITLE
Nugets should not reference facade assemblies as framework dependencies

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [aspnet/DataProtection#117]
Referencing System.IO and other facade assemblies in the nuget metadata fails on .NET 4.5.1 installations. Remove System.IO from the metadata:

> &lt;?xml version="1.0" encoding="utf-8"?&gt;
> &lt;package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd"&gt;
>   &lt;metadata&gt;
>     &lt;id&gt;Microsoft.AspNet.DataProtection&lt;/id&gt;
>     &lt;version&gt;1.0.0-rc1-final&lt;/version&gt;
>     …
>     &lt;dependencies&gt;
>       …
>     &lt;/dependencies&gt;
>     &lt;frameworkAssemblies&gt;
>       ***&lt;frameworkAssembly assemblyName="System.IO" targetFramework=".NETFramework4.5.1" /&gt;***
>       &lt;frameworkAssembly assemblyName="System.Security" targetFramework=".NETFramework4.5.1" /&gt;
>       &lt;frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5.1" /&gt;
>       &lt;frameworkAssembly assemblyName="System.Xml.Linq" targetFramework=".NETFramework4.5.1" /&gt;
>       &lt;frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5.1" /&gt;
>       &lt;frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.1" /&gt;
>       &lt;frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5.1" /&gt;
>       &lt;frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5.1" /&gt;
>     &lt;/frameworkAssemblies&gt;
>   &lt;/metadata&gt;
> &lt;/package&gt;

**Comment by blowdart** [comment]
@Tratcher  can you take care of this once the general renaming stuff has settled down?

**Comment by muratg** [comment]
@davidfowl said he has some ideas to make this better in @pakrym's PR above (which was closed without merging.)  Moving to 1.0.0 milestone.  

@davidfowl please elaborate what you're thinking and we'll assign it to someone.

**Comment by davidfowl** [comment]
This is already fixed in the latest packages

**Comment by muratg** [comment]
:cool:

**Comment by mattscully** [comment]
@davidfowl Is there a target release date for rc2?  I am unable to install package Microsoft.AspNet.WebHooks.Custom.SqlStorage 1.2.0-rc1b which depends on this DataProtection package because of this issue.  Or is there a work around?

**Comment by mattscully** [comment]
Looks like I found my answer: https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/
