### ISSUE TITLE
Rename Microsoft.AspNetCore.Cryptography.Internal

### ISSUE THREAD

**Issue by danroth27** [aspnet/DataProtection#118]
Microsoft.AspNetCore.Cryptography.Internal [ships publicly](https://www.nuget.org/packages/Microsoft.aspnet.cryptography.internal) on nuget.org, but it has a package ID with the word "internal" in it. If customers are supposed to use this package then it's ID probably shouldn't have "internal" in it.

**Comment by muratg** [comment]
@Eilon any name suggestions?  .Utils?

**Comment by Eilon** [comment]
I actually like `.Internal` because literally everything in there is internal. I don't think customers ever reference this package directly.

But if we really don't like that then I guess we can do `.Utils`, though it's awful.

**Comment by muratg** [comment]
Yeah, I now remember the decision to use .Internal package and namespace names and keeping classes public and testable.  @danroth27 closing this one, reopen if you disagree.
