### ISSUE TITLE
Make DataProtection follow the Options model

### ISSUE THREAD

**Issue by javiercn** [aspnet/DataProtection#121]
This repo requires some cleanup to adapt it to the pattern we follow on other parts of the framework

**Comment by GuardRex** [comment]
@javiercn ... friendly reminder from those of us in production with bits like ...
```c#
services.AddSingleton<IXmlRepository, CustomXmlRepository>();
services.AddSingleton<IXmlEncryptor, CustomXmlEncryptor>();
services.AddSingleton<IXmlDecryptor, CustomXmlDecryptor>();
```
... let us know if "follow the Options model" means something is about to break (i.e., Announcements repo). Everything here is staged, but surprises can be unsettling.

**Comment by Eilon** [comment]
@GuardRex indeed, we'll post announcements about any significant changes - and if we push this change through, it'll count as significant.

**Comment by GuardRex** [comment]
@Eilon Cool. I have several apps in production now using these bits. Although everything is staged and tested, it still puts a scare on you :skull: when something unexpectedly goes :boom:.
