### ISSUE TITLE
Changing key encryption settings won't be used if current valid key exists on FileSystem

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/DataProtection#143]
Run an app with:
`services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo("MyDirectory");`
to create a key on the filesystem, then decide to add some encryption like:
`services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo("MyDirectory").ProtectKeysWithDpapi();`
A new key wont be created, and the old key will still be used.

**Comment by blowdart** [comment]
By design - you would specifically have to revoke a key for it not be used any longer, and any valid key in the key ring can be chosen and used, regardless of protection.

**Comment by BrennanConroy** [comment]
Alright, but should it still create a new key based on your new specifications?

**Comment by blowdart** [comment]
Not until the "current" one expires.
