### ISSUE TITLE
Port BlobStorage sample into an official package

### ISSUE THREAD

**Issue by blowdart** [aspnet/DataProtection#145]
And while we're at it, write a SQL one too.

https://github.com/GrabYourPitchforks/DataProtection.Azure/tree/dev/DataProtection.Azure

**Comment by pakrym** [comment]
Issues with Azure Key Vault:
0. Absence of netstandard version of package
1. How to sync distributed writes to secret?
2. More efficient ways of enumerating secrets then loading multi-part list and then getting each one by id.

**Comment by pakrym** [comment]
https://github.com/aspnet/DataProtection/pull/163
