### ISSUE TITLE
Unique-ify the names of the various ServiceCollectionExtensions types

### ISSUE THREAD

**Issue by Eilon** [aspnet/DataProtection#148]
Currently they conflict with type names in other assemblies and/or have super generic names (thus making the names somewhat useless). We should always give these types reasonably unique names describing not only what they extend, but what type of functionality they add.

Proposal:
* Rename [this](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/DataProtectionExtensions.cs) to `DataProtectionUtilityExtensions` (this name is awful, but the method on here is super obscure)
* Rename [this](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionExtensions.cs) to `DataProtectionAdvancedExtensions` (another awful name, but I used up all the good names already 😄)
* Rename [this](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection.Abstractions/DataProtectionExtensions.cs) to `DataProtectionCommonExtensions`

**Comment by Eilon** [comment]
@danroth27 FYI

**Comment by NTaylorMullen** [comment]
cc9873ae6c71fc613851e9999b50edeec5dc9e3e
