### ISSUE TITLE
Discussion: DependencyInjection protection extension classes have been renamed to avoid ambiguity

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/DataProtection#150]
Format: _Microsoft.AspNetCore.DataProtection.*_  

| Package | Old Type Name | New Type Name |
| --- | --- | --- |
| Abstractions | DataProtectionExtensions | DataProtectionCommonExtensions |
| Extensions | DataProtectionExtensions | DataProtectionAdvancedExtensions |
| Primary Package | DataProtectionExtensions | DataProtectionUtilityExtensions |

Announcement issue: https://github.com/aspnet/Announcements/issues/187

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
