### ISSUE TITLE
Cannot unprotect data after migrating from RC1 to RC2

### ISSUE THREAD

**Issue by aplex** [aspnet/DataProtection#153]
After upgrading from RC1 to RC2 , previously protected data cannot be unprotectedю

IDataProtector.Unprotect throws an exception that have the following inner exception:

"Could not load file or assembly 'Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.":"Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"

So it tries to load assembly with old naming from RC1, although it is not mentioned in project.json

The old assembly name is mentioned in xml files at c:\Users\%username%\AppData\Local\ASP.NET\DataProtection-Keys

OS: windows 10 x64

**Comment by aplex** [comment]
No sure what the payload is. I'm calling protect/unprotect with the plain strings as parameters.

And the xml files look like that:

```
<?xml version="1.0" encoding="utf-8"?>
<key id="XXX" version="1">
  <creationDate>2016-02-15T00:17:23.317857Z</creationDate>
  <activationDate>2016-02-15T00:17:23.2923209Z</activationDate>
  <expirationDate>2016-05-15T00:17:23.2923209Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNet.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <encryptedSecret decryptorType="Microsoft.AspNet.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" xmlns="http://schemas.asp.net/2015/03/dataProtection">
        <encryptedKey xmlns="">
          <!-- This key is encrypted with Windows DPAPI. -->
          <value>YYY</value>
        </encryptedKey>
      </encryptedSecret>
    </descriptor>
  </descriptor>
</key>
```

**Comment by davidfowl** [comment]
Looks like it....

**Comment by blowdart** [comment]
Yea,

https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/KeyManagement/XmlKeyManager.cs#L378

I guess we could hack the de-encryption for that special case. Of course we say this for ephemeral data you're not worried about loosing but ...

**Comment by blowdart** [comment]
@muratg

**Comment by muratg** [comment]
Not sure what to do here. It looks like RC2 to RTM will also have similar problem (due to PublicKeyToken in the `decryptorType`)

@blowdart any proposal?

**Comment by blowdart** [comment]
What changed there?

You're just going to have to have a type alias / fowarder type thing to allow old keys to still function. As the keys are only read once it's not going to be that painful performance wise.

**Comment by muratg** [comment]
Sorry, my bad -- PublicKeyToken won't be changing obviously, and since we're not going to rename the namespace or the types again, RC2 to RTM should NOT have this problem.

Good to close?

**Comment by blowdart** [comment]
No, you need to support this migration scenario. People will go from RC1 to RTM and loose data. You really need to push an update for this asap so people coming from RC1 to RC2 don't loose data either.

**Comment by pakrym** [comment]
@aplex can you please try with latest version of ASP.NET `1.0.0-rc3-21233`. With https://github.com/aspnet/DataProtection/pull/157 data should be unprotected successfully.

**Comment by aplex** [comment]
I tried to use some libraries from RC3 to work around another bug, and could not get dotnet restore to work - probably need all dependencies to be updated to use RC3 as well.

For this problem I made a hacky workaround several days ago - the xml file with the keys was patched to use the new namespaces and assembly names. This patching happens before the keys are loaded. Seems to work ok for the moment.

**Comment by pakrym** [comment]
I'm closing this issue as it should be fixed by #157

**Comment by JunTaoLuo** [comment]
@danroth27 we probably need to add this to the rc1 to rc2 migration docs too. And test this in future migration sign-off scenarios.

**Comment by danroth27** [comment]
I'm not sure what we would document other than to wait for RTM or grab a dev build.

**Comment by JunTaoLuo** [comment]
Ah yes, that's what I meant. We should indicate that this is a known issue and we specifically added something in 1.0.0 for it. We should also test this in the upcoming sign offs.
