### ISSUE TITLE
Share protected data between multiple machines

### ISSUE THREAD

**Issue by alfhv** [aspnet/DataProtection#156]
I have a few instances on my service running on different machines. I have a problem, the data protected by one machine can't be unprotected by other one. Error message is something like:

The key is not in security ring...

How did I need to configure the dataprotector to ensure any instance can access the data ?

The code on each instances is exactly the same, the purpose also of course. I'm creating the protector using the very basic code provided in samples.

**Comment by GuardRex** [comment]
You can use an UNC share and encrypt keys at rest with an X.509 certificate ...
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection();
    services.ConfigureDataProtection(configure =>
    {
        configure.PersistKeysToFileSystem(new DirectoryInfo(@"\\server\share\directory\"));
        configure.ProtectKeysWithCertificate("thumbprint");
    });
}
```
https://docs.asp.net/en/latest/security/data-protection/configuration/overview.html#data-protection-configuring

... and there are some more "exotic" possibilities as well. You can glean some info on other approaches here: https://github.com/aspnet/DataProtection/issues/92

**Comment by alfhv** [comment]
question: if I use this config:

```
services.ConfigureDataProtection(configure =>
      {
          configure.PersistKeysToFileSystem(new DirectoryInfo(@"\\server\share\directory\"));
          configure.ProtectKeysWithDpapi();
      });
```

and all instances runs under the same AD account on all server, then the key (and the data protected) will be accesible to all instances ??

**Comment by alfhv** [comment]
as I dont have a common certificate on all machines, I would like to rely on other solution, like AD account but after tried it doesn't work. (using config on previous post)

any help on this ?

**Comment by GuardRex** [comment]
@alfhv Azure Blob Storage? RC2 version provided by @cwe1ss based on work by @GrabYourPitchforks: https://github.com/GrabYourPitchforks/DataProtection.Azure/pull/1

**Comment by hotchkj** [comment]
If @alfhv uses AWS, I recently wrote a similar storage & encryption solution in hotchkj/AspNetCore.DataProtection.Aws#1. Currently RC1, though I intend to get to porting over to RC2 fairly soon.

**Comment by muratg** [comment]
Putting in post RTM to re-triage.

**Comment by muratg** [comment]
@blowdart Thoughts?

**Comment by blowdart** [comment]
I've already said we need this post RTM and someone promised to create an issue. It's post RTM.

We need providers for EF backed databases, and for Azure table storage.

See https://github.com/aspnet/DataProtection/issues/145

For AD you can use the [ProtectKeysWithDpapiNG](https://docs.asp.net/en/latest/security/data-protection/implementation/key-encryption-at-rest.html). DPAPI-NG is mean to roam keys via active directory.

**Comment by muratg** [comment]
Dup of #145
