### ISSUE TITLE
Can old storage in XML repositories be cleaned up?

### ISSUE THREAD

**Issue by hotchkj** [aspnet/DataProtection#158]
Apologies if this has been covered in earlier issues, but I couldn't find a good reference in the docs or here. If one is implementing IXmlRepository (I'm writing one to use AWS S3), it essentially has two calls - GetAllElements and StoreElement.

- What's the right thing to do as this operates over time, to avoid unbounded disk/database/storage usage?
- When can old elements be cleaned up, if at all?
- Is this better done in GetAll or Store or asynchronously?

Thanks in advance.

**Comment by muratg** [comment]
@blowdart Something we should consider. I don't think we have a clean-up story. Files are not huge so shouldn't be a big problem in the short-medium term.

**Comment by blowdart** [comment]
No we shouldn't. This is on purpose. If you delete keys then any data that is encrypted with them can no longer be decrypted. As we don't know what users have done with keys, and any data is still available we cannot do this.

So, no cleanup.
