### ISSUE TITLE
Move AzureDataProtectionBuilderExtensions of Azure.Blob to namespace Microsoft.AspNetCore.DataProtection

### ISSUE THREAD

**Issue by troydai** [aspnet/DataProtection#179]
Keep inline with:

https://github.com/aspnet/DataProtection/blob/eb1745332202ad32467d905d2c900b5dd8c45f08/src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs

https://github.com/aspnet/DataProtection/blob/b340b0f0f73db72045b3c6577eaff60b5772906d/src/Microsoft.AspNetCore.DataProtection.Redis/RedisDataProtectionBuilderExtensions.cs

**Comment by pakrym** [comment]
Done https://github.com/aspnet/DataProtection/blob/6eacfd2679685085e0d7e106634e2dd17bd2381b/src/Microsoft.AspNetCore.DataProtection.AzureStorage/AzureDataProtectionBuilderExtensions.cs#L12
