### ISSUE TITLE
Microsoft.AspNetCore.Cryptography.KeyDerivation dependencies

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/DataProtection#186]
Hi,
the old V1.0 of this package worked just fine in .NET Framework 4.5.1/4.6.1 without many dependencies (only Microsoft.AspNetCore.Cryptography.Internal and that one had no dependencies)
The new V1.1 has a fixed dependency on  NETStandard.Library (>= 1.6.1)  and now quite a few extra nuget packages are necessary on .NET Framework 4.5.1/4.6.1.
Is it really necessary that the full .NET Standad library is now required for .NET Framework 4.5.1, as far as I see there are no changes to the actual source code of key derivation which would warrant that massive depdency.

This package is very useful outside of asp.net core, because it provides fast PBKDF2 with multiple hmac algorithms.

**Comment by blowdart** [comment]
This is a side effect of how asp.net now aligns to the .NETStandardLibrary. Eventually trimming might come along as part of the build process, but that's really up to .NET Core.

**Comment by SparkyWindTalker** [comment]
Quick question, does Microsoft.AspNetCore.Cryptography.KeyDerivation (with the different hash algorithms, SHA256, SHA512, etc.) still work in .NET Framework 4.5.1/4.6.1 projects?
