### ISSUE TITLE
[Question] load balancing\rolling cluster updates\rollbacks

### ISSUE THREAD

**Issue by KLuuKer** [aspnet/DataProtection#188]
when deploying my app with a new version of data protection, for arguments sake let's say 1.1.0

 it will create a new master key with version 1.1.0 and it will start using that key for all data that needs to be encrypted. great i like new fresh keys, but.....

when only part of the cluster is updated and people are getting load balanced to a part that has not been updated yet or when doing a rollback (because of some other code\external issue)
it would fail to load the new 1.1.0 assembly (for example with sessions encrypted and stored in a cookie)

then it would be nice to have some kind of mechanism to specify you want to keep running on 1.0.0 and after everything works one could change some config setting that the maximum version should be 1.1.0

**Comment by blowdart** [comment]
This is finally fixed in 2.0. Apologies for this. So once everything gets updated to 2.0, then this shouldn't happen going forward, unless, for example, in v3 we end up using an entire new class, well then everything would have to be pulled up to v3.
