### ISSUE TITLE
Asp.Net MVC Core: “Error unprotecting the session cookie” exception

### ISSUE THREAD

**Issue by skorunka** [aspnet/DataProtection#189]
I have an Asp.NET MVC application with this Authentication setup:

ConfigureServices():

    services.AddSession()
    services.AddAuthentication(sharedOptions => sharedOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);

Configure():

			app.UseCookieAuthentication(new CookieAuthenticationOptions());
			app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
			{
				ClientId = "xx",
				Authority = "xx",
				Events = new OpenIdConnectEvents { OnRemoteFailure = this.OnAuthenticationFailed }
			});

			app.UseSession();

When hosted in IIS, some users get this exception:

    Microsoft.AspNetCore.Session.SessionMiddleware, 
          Error unprotecting the session cookie.
    System.Security.Cryptography.CryptographicException: The key {9ec59def-874e-45df-9bac-d629f5716a04} was not found in the key ring.
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
       at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

I have run this on the hosting server https://github.com/aspnet/DataProtection/blob/dev/Provision-AutoGenKeys.ps1

Web has only HTTPS binding, SSL certificate is ok and signed. What might cause this issue? What actually is that "key" value?

**Comment by skorunka** [comment]
I can also see a lot of these:
11/30/2016 18:10:28:warn: Microsoft.AspNetCore.Session.DistributedSession[2]
      Accessing expired session, Key:21d8f9ed-4013-2e65-d884-651a6f0060a0

**Comment by kalluri-nb** [comment]
Any update on this. This is happening in cluster a lot. A session cookie value created on one instance is unable able to be unprotected by a different instance. Is there any basic setup for DataProtectionOptions for session management in cluster.

**Comment by skorunka** [comment]
The machine is not in a cluster or farm. Each requested is server by the same machine, by the same IIS site.

**Comment by kalluri-nb** [comment]
We resolved it by adding the redis as persistence store using DataProtectionBuilder.

**Comment by skorunka** [comment]
@kalluri-nb Nice, how can I resolve it? What should I change in the Setup.cs?

**Comment by warrenfp** [comment]
@kalluri-nb: Can you share your implementation?

**Comment by blowdart** [comment]
@skorunka Where are your keys being persisted? This is strange, it looks like the keyring can't get created at all. Have you tried, as a stop gap, persisting the keyring to the file system anywhere?

**Comment by skorunka** [comment]
@blowdart Hi, I'm using defaults. How can I setup where the keys are persisted? Or how can I know where they are actually persisted?

**Comment by blowdart** [comment]
It tries to figure out the right place depending on machine configuration. The log files will tell you, if you're logging at informational.

**Comment by 1amirjalai** [comment]
@kalluri-nb what do you mean by 

> We resolved it by adding the redis as persistence store using DataProtectionBuilder.

could you please show an example?

**Comment by 1amirjalai** [comment]
@blowdart may this issue an issue #228 are related

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2520
