### ISSUE TITLE
DataProtection concrete class deprecated?

### ISSUE THREAD

**Issue by salmankhann** [aspnet/DataProtection#191]
Hello, the docs on the [Non-DI Aware page]((https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/non-di-scenarios)) states that we should be using DataProtection class directly but I'm unable to find that class. I'm targeting NetStandard.Library 1.6.1 and AspnetCore.MVC 1.1.0

What should I do as an alternative? Thanks.

**Comment by ajaybhargavb** [comment]
I think you mean the `DataProtectionProvider`. If so you need to reference `"Microsoft.AspNetCore.DataProtection.Extensions"` in your project.json.
