### ISSUE TITLE
[Question] Why is Protect(string) and Unprotect(string) not part of IDataProtector?

### ISSUE THREAD

**Issue by Legogris** [aspnet/DataProtection#202]
When writing unit tests, it helps a lot being able to mock the results of these functions depending on the input.

Right now it is a big hassle doing this since we have to mock the byte-array versions and then mimic the internal implementations of the extension methods in `DataProtectionCommonExtensions`. I can't even get it to work properly for a particular use case. It would be very beneficial to have the directly on the interface.

**Comment by blowdart** [comment]
What are you unit testing here? Your own data protection implementation?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2518
