### ISSUE TITLE
Fix doc comments and add null checks

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/DataProtection#207]
Follow up to #134 

Need to review doc comments for the public class and update them as necessary along with adding null checks.

Example:
https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/EphemeralDataProtectionProvider.cs#L27

**Comment by muratg** [comment]
@ajaybhargavb will you get to this in the next few days?

**Comment by ajaybhargavb** [comment]
> @ajaybhargavb will you get to this in the next few days?

Yes

**Comment by ajaybhargavb** [comment]
This was mostly already done as part of other issues like #247. I've sent a PR with the missed stuff.

**Comment by ajaybhargavb** [comment]
379d6d8dcd046fb31632e29bbaa4038bcd3895a5

**Comment by ajaybhargavb** [comment]
Remaining related issue. https://github.com/aspnet/Docs/issues/2975
