### ISSUE TITLE
KeyRingBasedDataProtector> repeated validate code

### ISSUE THREAD

**Issue by tnclong** [aspnet/DataProtection#210]
https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyRingBasedDataProtector.cs#L94

https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyRingBasedDataProtector.cs#L100

**Comment by davidfowl** [comment]
Good catch! Do you want to send a PR to fix it?
