### ISSUE TITLE
Implement support for cloud DPAPI

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/DataProtection#22]
Currently Antares and most other hosting providers store machine keys in plain text in applicationHost.config. We store our keys in %HOME%, but still in plain text. We can't use DPAPI because it's not meant for scale-our scenarios such as these. We need to convince Antares and other hosters to make a CryptProtectData-like API for our consumption. One possible implementation would be for us to read a DLL path from the system registry, then to look for a CryptProtectData-like export from that module.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2529
