### ISSUE TITLE
Revisit how application identifier is generated

### ISSUE THREAD

**Issue by Eilon** [aspnet/DataProtection#229]
Perhaps in the case of IIS (and thus Antares), ANCM should flow the IIS "app id" so that Data Protection could use it.

cc @blowdart @DamianEdwards @davidfowl @Tratcher

**Comment by blowdart** [comment]
This is probably a hosting issue

**Comment by Tratcher** [comment]
or ANCM + IISIntegration

**Comment by davidfowl** [comment]
We need to also consider xplat and service fabric scenarios (clusters in general).

/cc @glennc

**Comment by johnkors** [comment]
Are we talking about [DataProtectionUtilityExtensions](https://github.com/aspnet/DataProtection/blob/rel/1.0.3/src/Microsoft.AspNetCore.DataProtection/DataProtectionUtilityExtensions.cs#L42) ? 

It's by default causing invalidation of cookies when used in conjunction with Octopus, which deploys to a different physical path every deploy. 

@anderaus wrote a piece about the issues here: http://blog.novanet.no/a-pile-of-anti-forgery-cookies/

**Comment by davidfowl** [comment]
Yes, it's a really bad default.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2512
