### ISSUE TITLE
[1.0.x] Version-insensitive type activation on .NET Framework

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DataProtection#235]
Consider backporting the fix for https://github.com/aspnet/DataProtection/issues/187 to 1.x. The fix was added to 2.0.0 in this PR: https://github.com/aspnet/DataProtection/pull/223

cc @Eilon

**Comment by Tratcher** [comment]
This issue impacts the ability of 2.0 and 1.1 apps to share auth cookies. https://github.com/aspnet/Release/issues/181

**Comment by Eilon** [comment]
Changed this bug to be 1.0.x-specific, and logged https://github.com/aspnet/DataProtection/issues/265 to be 1.1.x-specific. That way we make sure to fix it everywhere (if we take this fix).

For future reference: please don't set any labels, the triage team will do that.

**Comment by Eilon** [comment]
This patch is *approved* for 1.0.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by Eilon** [comment]
@natemcmaster all yours.

**Comment by natemcmaster** [comment]
Resolved in https://github.com/aspnet/DataProtection/pull/268. This fix will be in the 1.0.4 patch update of DataProtection (when that is released).
