### ISSUE TITLE
[1.x] KeyRingProvider initialization causes thread pool starvation when server starts under load

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DataProtection#242]
Consider back-porting https://github.com/aspnet/DataProtection/pull/241 to 1.x.

cref original issue #233 (fixed for 2.0)

**Comment by brockallen** [comment]
Sorry, repeating from the PR:

> Ok, thanks. One my my customers was on the original issue/thread here, and from their perspective data protection is in essence broken and unusable until this fix makes it into a release (as I'd imagine anyone else trying to use data protection, especially in azure). They aren't really in a position to move to 2.0 anytime soon.

**Comment by Tratcher** [comment]
Looks like there's a trivial workaround, does it have any catches?

**Comment by brockallen** [comment]
> Looks like there's a trivial workaround, does it have any catches?

Well, I can only say that my customer was close to dropping ASP.NET Core support (and going back to the ancient days of Katana even!) given that this felt like a critical issue "out of the box". Perhaps fixing perception is more important?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2510
