### ISSUE TITLE
Validate Redis extension for shipping

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DataProtection#254]
Microsoft.AspNetCore.DataProtection.Redis ships as a 0.x version (which means it's pseudo-unsupported.) It also does not ship in the runtime store.

Verification items to complete before we ship a "supported" version:

 - Add functional tests that actually use a real Redis server to pull keys
 - Update version number
 - Add to ASP.NET Core runtime store
 - Add API baselines ( #232 )

**Comment by Vlaaaaaaad** [comment]
Hi, is this still planned? Is there an ETA for it?

**Comment by natemcmaster** [comment]
It's not high on our priority list and we haven't assigned this a milestone yet. But I would welcome PRs to add functional tests and improve the quality of the extension.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2509
