### ISSUE TITLE
[1.1.x] Version-insensitive type activation on .NET Framework

### ISSUE THREAD

**Issue by Eilon** [aspnet/DataProtection#265]
See https://github.com/aspnet/DataProtection/issues/235

**Comment by Eilon** [comment]
This patch is *approved* for 1.1.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by natemcmaster** [comment]
Resolved in https://github.com/aspnet/DataProtection/pull/269.

This fix will be available in the 1.1.3 patch of DataProtection.
