### ISSUE TITLE
Using an in-memory repository. Keys will not be persisted to storage.

### ISSUE THREAD

**Issue by Jenan** [aspnet/DataProtection#271]
Hello,

I have deployed my .net core application to shared hosting with default settings of DataProtection like this:

```
services.AddDataProtection();
```

I get these errors (warrnings):

ID | Level | Logged | Message | Logger | Callsite
-- | -- | -- | -- | -- | --
2476 | Warn | 8/27/2017 5:20:28 AM | No XML encryptor configured. Key {08660da7-762e-40a4-90bd-2b18081e0af4} may be persisted to storage in unencrypted form. | Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager | Microsoft.Extensions.Logging.LoggingExtensions.NoXMLEncryptorConfiguredKeyMayBePersistedToStorageInUnencryptedForm
2475 | Warn | 8/27/2017 4:00:49 AM | Using an in-memory repository. Keys will not be persisted to storage. | Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository | Microsoft.Extensions.DependencyInjection.DataProtectionServices+<>c.<GetDefaultServices>b__0_1
2474 | Warn | 8/27/2017 4:00:47 AM | Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. | Microsoft.Extensions.DependencyInjection.DataProtectionServices | Microsoft.Extensions.DependencyInjection.DataProtectionServices+<>c.<GetDefaultServices>b__0_0

I can see the strange behavior of my application if I have loggin in my application and use the option remember my login - next day if I try enter to the site the system can't read this persistent cookie but in browser is stored correctly - like if the system can't decrypt the cookie but it's only my idea.

How can I solve this issue please?

I have uses these packages:
```
<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.2" />
<PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
<PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1">
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0">
<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.2" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.1" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.2" />
<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0">
```

**Comment by blowdart** [comment]
Are you on Linux by any chance?

We try to figure out where we can store things but when we can't work it out, or the OS doesn't have any reasonably secure defaults we fall back to in memory. In this case you need to make decisions about where you want to persist keys using the [configuration extensions](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x). So you'd choose to persist to the file system, outside of your web root obviously, and then protect with a certificate. Or shove them in Azure blob storage and use Azure Key Vault.

**Comment by Jenan** [comment]
The application is running on shared hosting with IIS, on windows server. I don't have any access to configuration of IIS. I have tried to use the store of keys on the file system that seems solve these warrning but I have a .Net Core 1.1.  and I can't find a method for encrypt using certificate, probable this feature is available - how can I encrypt the keys in version 1.1.? 
Thank you for suggestions.

**Comment by blowdart** [comment]
Unfortunately it's only available in 2.0, unless you target .NET Desktop.

If you are only planning to run on one server you could use DPAPI instead.

**Comment by Jenan** [comment]
I solved this issue using storing dataprotection keys to file system.

**Comment by KuPinsIT** [comment]
I resolved this issue when i edit application pool as below:
https://cypressnorth.com/programming/solved-using-memory-repository-keys-will-not-persisted-storage-asp-net-core-iis/
