### ISSUE TITLE
External DI Container issue

### ISSUE THREAD

**Issue by ipjohnson** [aspnet/DataProtection#274]
I'm having an issue with the refactoring as part of [this PR](https://github.com/aspnet/DataProtection/commit/cde3b96aa7d1e51414ab02dc2c8f22649b595da3)

The problem is for any container that allows concrete types to be automatically resolved (most allow this to happen) the wrong constructor will chosen for [KeyManagementOptionsSetup](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection/Internal/KeyManagementOptionsSetup.cs)

This all stems from the issue raised [here](https://github.com/ipjohnson/Grace/issues/116). Normally I'd just have the user work around it but with the type being internal there isn't an easy work around. I can have the person turn off automatic registration but that's a pain and really isn't going to work for certain situations. 

What seems like the proper solution is to make the RegistryPolicyResolver parameter an interface rather than passing around the actual type. @davidfowl any thoughts?

**Comment by davidfowl** [comment]
This came up here https://github.com/aspnet/DataProtection/issues/270 as well. I think we should fix it. However, we can't make any breaking changes in patches so we'd probably have to add another ctor.

/cc @muratg @Eilon @DamianEdwards

**Comment by muratg** [comment]
@pakrym could you please take a look to see what's the best way to fix this without a breaking change?

**Comment by davidfowl** [comment]
Actually we don't add APIs in patches either, this might need to be a 2.1 thing.

**Comment by muratg** [comment]
@davidfowl Yup, it's triaged in 2.1.

**Comment by davidfowl** [comment]
@muratg It might be possible to patch this since these types are internal.

**Comment by Eilon** [comment]
Which internal API is it and from where are the internal APIs called? Even in patches we are careful about changing internal APIs if they're used in other product assemblies and not just tests.

**Comment by davidfowl** [comment]
Here https://github.com/aspnet/DataProtection/blob/ee009982dc96171cf62ab4542aaf7c9cff984390/src/Microsoft.AspNetCore.DataProtection/Internal/KeyManagementOptionsSetup.cs#L14
