### ISSUE TITLE
Consider normalizing path used for Discriminator

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/DataProtection#276]
https://github.com/aspnet/DataProtection/blob/46dadbb18683164a918873f43624aee3b5b0510c/src/Microsoft.AspNetCore.DataProtection/Internal/HostingApplicationDiscriminator.cs#L23

One specific instance where I hit this was running an app from the command line produced a cookie in my browser. And then running the exact same app without any changes from VS Code would fail to unprotect the cookie because VS Code environment returned `e:/...` and command line environment returned `E:/...`

**Comment by blowdart** [comment]
This would probably end up being platform specific - because it shouldn't be case sensitive on windows, but should on linux.

Is there a path normalization function? (You'd be doing the work yourself anyway)

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2507
