### ISSUE TITLE
Ensure KeyVault Provider is compatible with automatic KeyVault light-up

### ISSUE THREAD

**Issue by anurse** [aspnet/DataProtection#279]
Azure Web Apps and VMs have the ability to be associated with a KeyVault and have the connection information light-up automatically (without requiring the app to specify a certificate or key). We should make sure the data protection provider for Key Vault supports this (it requires some changes in the KeyVault client, apparently)

See @glennc for details.

/cc @muratg

**Comment by muratg** [comment]
@pakrym please ping @glennc.

**Comment by pakrym** [comment]
Hosting startup uses MSI and `Microsoft.Azure.Services.AppAuthentication`
