### ISSUE TITLE
Create SQL XmlRepository

### ISSUE THREAD

**Issue by janpieterz** [aspnet/DataProtection#280]
Would make sense as it's one of the most common shared pieces of infrastructure between multiple servers.

It's mentioned in https://github.com/aspnet/DataProtection/issues/145 but doesn't seem to have been built.

**Comment by blowdart** [comment]
@muratg It's worth doing, but I think trying to make it generic, or indeed EF model based might be more bother than its worth. A straightforward SQL, with parameterised queries would do it.

**Comment by urbanhusky** [comment]
I'm trying to implement such a repository and I use EF. I struggle with figuring out how to properly resolve the corresponding `DbContext`. The context would be registered as _scoped_ in the DI container, but I don't know how the repository is being registered - or if I would have to register it myself.

I do the following:
```C#
// Register db context
services.AddDbContext<DataProtectionDbContext>(
    opts =>
    {
        var dpapiMigrationsAssembly = typeof(DataProtectionDbContext).GetTypeInfo().Assembly.GetName().Name;
        opts.UseSqlServer(dpapiConnectionString, b => b.MigrationsAssembly(dpapiMigrationsAssembly));
    });

// configure dpapi
services.AddDataProtection()
    .ProtectKeysWithCertificate(GetCertificate()) // no support for rollover or revocation when using certificate?
    .AddKeyManagementOptions(options => options.XmlRepository = new SqlDatabaseXmlRepository(/* TODO: how to resolve? Repository needs to be an instance and any DI would be for *right now* */))
```

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2505
