### ISSUE TITLE
SHA-3

### ISSUE THREAD

**Issue by CShepartd** [aspnet/DataProtection#283]
Do you plan add SHA-3 in `Pbkdf2`? (`Microsoft.AspNetCore.Cryptography.KeyDerivation`)

Acctually in `Pbkdf2` aviable is only `HMACSHA1`, `HMACSHA256`, and `HMACSHA512`

**Comment by blowdart** [comment]
As we rely on the CLR for crypto that would be an issue best asked of https://github.com/dotnet/corefx. Once they add it we'd look at using it.
