### ISSUE TITLE
Consider adding AspNetCore.DataProtection.ServiceFabric to the documented options

### ISSUE THREAD

**Issue by MedAnd** [aspnet/DataProtection#289]
Consider adding [AspNetCore.DataProtection.ServiceFabric](https://github.com/MedAnd/AspNetCore.DataProtection.ServiceFabric) as an option?

**Comment by blowdart** [comment]
We don't appear to have a page for 3rd party providers that I can see on the docs site. Am I missing something?

**Comment by MedAnd** [comment]
Hi @blowdart,

On the [Key storage providers](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers) page there is a references to another 3rd party library,  [StackExchange.Redis ConnectionMultiplexer](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Basics.md)... not the same I know but wondering if you would consider links to 3rd party key providers?

**Comment by blowdart** [comment]
That's slightly different, as we wrote the providers here, just not the backing store. Given the sensitivity of the library I'm not sure I'd be comfortable seeing something in official docs pointing to a 3rd party. However if you look at identity, https://github.com/aspnet/identity you can see we have 3rd party options in the repo home page. Would that work for you?

**Comment by MedAnd** [comment]
Understand re: sensitivity in official docs, especially around security related components. Worth asking though as I noticed other teams such as EF Core team have 3rd party providers listed on the [Database Providers](https://docs.microsoft.com/en-us/ef/core/providers/) page. They used a warning such as:

![image](https://user-images.githubusercontent.com/13365135/33994872-39003ff0-e130-11e7-8f12-351e37a1303c.png)

I think it would help the .Net Core community to at least have a new section, maybe "Community Maintained Key Providers" in [aspnet/DataProtection](https://github.com/aspnet/DataProtection) if that is acceptable?

**Comment by blowdart** [comment]
I'd rather do the same as identity and keep it in the source repo rather than docs,

**Comment by MedAnd** [comment]
Did you want a pull request to update the repo landing page or you guys will?

**Comment by blowdart** [comment]
Done.
