### ISSUE TITLE
Enable scenario with RSA certificate not being stored in the certificate store.

### ISSUE THREAD

**Issue by nenadvicentic** [aspnet/DataProtection#290]
Current implementation of `EncryptedXmlDecryptor` is dependent on the Windows certificate store.

While it is possible to specify "standalone" certificate for encryption for `CertificateXmlEncryptor` via constructor accepting `X509Certificate2`, `EncryptedXmlDecryptor` will search for the same certificate in the Windows certificate store based on it's thumbnail and crush.

All that is needed for this is to add additional line in `Decrypt` method of `EncryptedXmlDecryptor`:

```
            // Perform the decryption and update the document in-place.
            var encryptedXml = new EncryptedXml(xmlDocument);
            encryptedXml.AddKeyNameMapping(x509Certificate2.Thumbprint, x509Certificate2.PrivateKey); // new line
            _decryptor.PerformPreDecryptionSetup(encryptedXml);
            encryptedXml.DecryptDocument();
```

Only thing missing would be to pass `X509Certificate2` to decryptor.

Currently, to achieve same thing, one has to make completely new implementation of `IXmlEncryptor`, `IXmlDecryptor` and related extension methods for `IDataProtectBuilder` configuration.

**Comment by blowdart** [comment]
@GrabYourPitchforks thoughts?

**Comment by GrabYourPitchforks** [comment]
Seems like a reasonable suggestion. The implementation isn't intended to be tied solely to the Windows cert store. It's just that nothing else was available when the APIs were created.

**Comment by blowdart** [comment]
@muratg Can we schedule this for 2.1?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2321
