### ISSUE TITLE
Secure way to store to a shared store

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/DataProtection#292]
How is this https://github.com/aspnet/DataProtection/issues/197 going? Was looking around as I'd like to encrypt our keys stored in redis with a cert.
Came across https://github.com/tillig/DataProtection but it's old, is there already a canonical way to do this in the framework?

**Comment by blowdart** [comment]
Certs work cross platform in 2.0, so it'd work for you. Protection is separate to storage, so you just layer it on.

**Comment by NinoFloris** [comment]
Alright great!
