### ISSUE TITLE
IXmlRepository contract to support removing elements

### ISSUE THREAD

**Issue by kosa-gyula-77** [aspnet/DataProtection#293]
Currently in version 2.0.1 _IXmlRepository_ implementers has to parse _XElement_ and determine its expiration date in order to remove expired elements from the underlying storage. Elements otherwise just get added but not removed.

**Proposal:**

IXmlRepository - or a new interface - exposes an additional method that allows the _XmlKeyManager_ to make regular house cleaning by removing expired and/or revoked elements, e.g.:

`void RemoveElement(string friendlyName);`

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2320
