### ISSUE TITLE
THIS ISSUE TRACKER IS CLOSED - use the Home repo issue tracker

### ISSUE THREAD

**Issue by Eilon** [aspnet/DataProtection#294]
Hello, this issue tracker is no longer used. Please log new issues here: https://github.com/aspnet/Home/issues

For information about this change, see https://github.com/aspnet/Announcements/issues/283

**Comment by natemcmaster** [comment]
See https://github.com/aspnet/DataProtection/pull/329. This repo is being made read-only. Use https://github.com/aspnet/AspNetCore from now own.
