### ISSUE TITLE
GetDefaultServices should not register OptionsServices

### ISSUE THREAD

**Issue by HaoK** [aspnet/DataProtection#31]
This is currently causing OptionsServices to be registered twice in kre apps since Hosting already adds OptionServices.  Unit tests should just add OptionsServices as part of their setup

**Comment by GrabYourPitchforks** [comment]
Looks like this was actually resolved by https://github.com/aspnet/DataProtection/pull/41.
@HaoK can you confirm and close the issue?

**Comment by HaoK** [comment]
Yeah also this bug is a bit obsolete, you can safely call AddOptions whenever you want now that we are using TryAdd everywhere, so...yeah this is moot now.
