### ISSUE TITLE
Consider adding AddDataProtection() extension method to add default DataProtection services to a service collection

### ISSUE THREAD

**Issue by divega** [aspnet/DataProtection#32]
It seems that DataProtection defines and provides the default implementation of services but unlike most other framework components it only defines `GetDefaultServices([IConfiguration])` method and not the `AddDataProtection(this IServiceCollection, [IConfiguration])`  sugar extension method. Adding the latter would improve consistency and would be useful for testing and for non-Web application scenarios that don't have Hosting (which adds DataProtectionServices.GetDefaultSErvices() implicitly) but still want to take advantage of these services using DI and a friendlier API.

**Comment by GrabYourPitchforks** [comment]
Closing out old bugs - this was resolved in https://github.com/aspnet/DataProtection/commit/f3e9381f165f6defd0384dfe78af64ccb3d03af0.
