### ISSUE TITLE
Key material should be able to be stored in a database

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/DataProtection#37]
This would be implemented as an additional IXmlRepository.

**Comment by GrabYourPitchforks** [comment]
Very difficult to make this generic - might be better as a sample? Can we do what Identity does for generic DB access?

**Comment by muratg** [comment]
Maybe better to have this as a sample.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2528
