### ISSUE TITLE
Consider remove security from name (Microsoft.AspNet.DataProtection)

### ISSUE THREAD

**Issue by HaoK** [aspnet/DataProtection#49]
The current naming is confusing as I assumed DataProtection depended on Security due to the naming when the exact opposite is true...

**Comment by HaoK** [comment]
cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
On the contrary, I think the Security base package is poorly named. It's weird to have a package with such a basic name as "Security" and have it be only AuthN. It doesn't cover cryptography, AuthZ, intrusion detection, or myriad other things that fall under the general umbrella of security. It might be better to rename all of the *.Security.* packages to *.Authentication.* instead.

**Comment by blowdart** [comment]
Time to break out the American Gladiator set so you can fight it out.

Alternatively, yea gotta side with Levi here. Now would be the time to break it and correct the naming of the security package.

**Comment by HaoK** [comment]
Yeah I don't disagree, I previously filed https://github.com/aspnet/Security/issues/131 to consider splitting security.  So maybe the only question is whether we want to keep the Security sub namespace anymore?

```
Microsoft.AspNet.[Security.]Authorization
Microsoft.AspNet.[Security.]Authentication[.Google|Facebook]
Microsoft.AspNet.[Security.]DataProtection
```

Thoughts? cc @lodejard @davidfowl @Tratcher

**Comment by lodejard** [comment]
I agree, the namespace Security is too general, Authentication is better for the authn schemes. The others names sound good too.

**Comment by GrabYourPitchforks** [comment]
Awesome. :)
FWIW, I agree with the original premise of this bug - we should remove the "Security" moniker from the DataProtection namespace. I'll get to this as part of the PBKDF2 refactoring.

**Comment by GrabYourPitchforks** [comment]
A note so I don't forget - Fowler suggested that `IDataProtector` and `IDataProtectionProvider` (and extension methods) be moved to their own interfaces package. I'm investigating the practicality of this.

**Comment by GrabYourPitchforks** [comment]
Committed as https://github.com/aspnet/DataProtection/commit/e2ca9fc6520d8189a398881e1b5bc394b2e76031.
