### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNet.Security.DataProtection'

### ISSUE THREAD

**Issue by cherrydev** [aspnet/DataProtection#54]
I'm opening this case so that other people who search for this error will hopefully encounter this and discover the solution!

In this particular case, I was using SignalR and had already exhaustively searched my entire hard drive for ANY remaining trace of any reference to "Microsoft.AspNet.Security.DataProtection".  After finally reading through about half the source code to DataProtection, I discovered that the reference to the class name had been cleverly hidden in an ENCRYPTED portion of an XML file stashed away in my %APPDATA% directory.

```
FileNotFoundException: Could not load file or assembly 'Microsoft.AspNet.Security.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
System.Type.GetType(String typeName, Boolean throwOnError)
Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager.ParseKeyElement(XElement keyElement)
Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.CreateCachedKeyRingInstanceUnderLock(DateTime utcNow, CachedKeyRing existingCachedKeyRing)
Microsoft.AspNet.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
Microsoft.AspNet.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] unprotectedData)
Microsoft.AspNet.SignalR.Infrastructure.DataProtectionProviderProtectedData.Protect(String data, String purpose)
```

This took me about 4 hours to track down the cause of!

When upgrading to the new version with the new assembly name, you MUST delete the contents of the directory: %APPDATA%\Local\ASP.NET\keys-BETA or you will end up with this error!  The xml file in this directory contains an encrypted representation of the assembly-qualified classname of the decryptor, which will be using the old "Security.DataProtection" assembly instead of the new one.

In order to mitigate the impact of this, I STRONGLY encourage the developers of DataProtection to include a guard that will prompt users to do this if the classname of the decryptor cannot be found, so nobody else needs to repeat my pain!

**Comment by Eilon** [comment]
For the sake of cross-referencing, here's the SO question/answer: http://stackoverflow.com/questions/28756390/could-not-load-file-or-assembly-microsoft-aspnet-security-dataprotection

@GrabYourPitchforks this is resolved with the changes in https://github.com/aspnet/DataProtection/commit/e4db4b1189f89e6737da7975581ddd4cf2a10d46, right?

**Comment by GrabYourPitchforks** [comment]
Yes. Dupe of https://github.com/aspnet/DataProtection/issues/53.

**Comment by cherrydev** [comment]
This doesn't actually seem like a dup of #53 since it's not resolved by updating "DataProtection, MVC, Security, and Identity references to latest" versions.  But it looks like e4db4b1 will fix it.

**Comment by GrabYourPitchforks** [comment]
Updating to latest included that commit when I made that comment. :)

**Comment by cherrydev** [comment]
Fair enough! :)
