### ISSUE TITLE
FileSystemXmlRepository depends on Windows environment variables when running on CoreCLR

### ISSUE THREAD

**Issue by ellismg** [aspnet/DataProtection#76]
In [FileSystemXmlRepository.cs, Line 106](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNet.DataProtection/Repositories/FileSystemXmlRepository.cs#L106) the code assumes that either LOCALAPPDATA or USERPROFILE exists.  If neither does, an ArugmentException will be thrown when ```Path.Combine``` is invoked, with ```null``` as an argument (since ```Environment.GetEnvironmentVarible``` returns null if the variable is not preset).

One could imagine changing the code to look like this:

```csharp
            // On core CLR, we need to fall back to environment variables.
            var localAppDataPath = Environment.GetEnvironmentVariable("LOCALAPPDATA");
            var userProfilePath = Environment.GetEnvironmentVariable("USERPROFILE");

            // On non-windows, these environment varibles are normally not present
            if (localAppDataPath == null && userProfilePath == null)
            {
                return null;
            }

            var folderPath = localAppDataPath ?? Path.Combine(userProfilePath, "AppData", "Local");
            DirectoryInfo retVal = GetKeyStorageDirectoryFromBaseAppDataPath(folderPath);
            try
            {
                retVal.Create(); // throws if we don't have access, e.g., user profile not loaded
                return retVal;
            }
            catch
            {
                return null;
            }
```

But it's not clear to me that's the right thing long term.

**Comment by GrabYourPitchforks** [comment]
Would it make sense to resurrect the `Environment.GetFolderPath` API on Core CLR and have the `SpecialFolders` enumeration contain an appropriate local app data-equivalent on non-Windows platforms?

FYI - the code base assumes Core CLR == Windows since it was created before the x-plat Core CLR announcements were public. You'll want to inspect all the ifdefs to be sure you catch all such assumptions.

**Comment by ellismg** [comment]
>Would it make sense to resurrect the `Environment.GetFolderPath` API on Core CLR and have the  `SpecialFolders`  enumeration contain an appropriate local app data-equivalent on non-Windows platforms?

Perhaps.  As the guy that would probably implement that, it's not clear to me what a sane default is.  On OSX, there's a concept of an Application Support folder, which is what we used for this API on Silverlight, but we had no concept of this on Unix.  If we were to do it, I suspect our best answer would end up just giving something back like `~/.coreclr`.  I'm not sure how we'll feel about bringing back APIs where we have to invent answers on other platforms.

> FYI - the code base assumes Core CLR == Windows since it was created before the x-plat Core CLR announcements were public. You'll want to inspect all the ifdefs to be sure you catch all such occurrences of this assumption in the code base.

I figured as much.  Thanks for the confirmation!
