### ISSUE TITLE
Pkg rename: Microsoft.AspNet.DataProtection.Interfaces -> Microsoft.AspNet.DataProtection.Abstractions

### ISSUE THREAD

**Issue by muratg** [aspnet/DataProtection#81]
See https://github.com/aspnet/Announcements/issues/8#issuecomment-97566113

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/DataProtection/commit/7ecbee2f7d05c056ef0948a7efadaf471f3c74b7
