### ISSUE TITLE
Is there a 1.0.0-beta4 version of this package?

### ISSUE THREAD

**Issue by david-peden-q2** [aspnet/DataProtection#82]
I only see beta4 packages when pointing at https://www.myget.org/F/aspnetvnext/api/v2/ and all are suffixed. https://www.myget.org/F/aspnetrelease/api/v2/ does not have a beta4 package. Is this intentional?

**Comment by Eilon** [comment]
The official package is here: http://www.nuget.org/packages/Microsoft.AspNet.DataProtection/1.0.0-beta4

The package on `aspnetvnext` are nightly builds so that should have beta5 by now. The `aspnetrelease` feed is used only for staging and testing, and is not meant to be used in general.

**Comment by Eilon** [comment]
BTW please note the packages were renamed from `Microsoft.AspNet.Security.DataProtection.*` to `Microsoft.AspNet.DataProtection.*`.

**Comment by davidfowl** [comment]
@Eilon Announcements?

**Comment by Eilon** [comment]
https://github.com/aspnet/Announcements/issues/15

**Comment by davidpeden3** [comment]
Thanks, @Eilon. I had not noticed the namespace change.
