### ISSUE TITLE
Add a nuget package for Microsoft.AspNet.Authentication.Cookies.Shareable?

### ISSUE THREAD

**Issue by imranbaloch** [aspnet/DataProtection#85]
I was read the doc http://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html and found a Microsoft.AspNet.Authentication.Cookies.Shareable package. But it is not available on nuget. It will be great if you guys support this package.

**Comment by blowdart** [comment]
@danroth27 / @Eilon

**Comment by blowdart** [comment]
I'd be inclined to keep that in their own packages, but it's a reasonable request. @danroth27 any comments?

**Comment by Eilon** [comment]
This is to share auth cookies between the previous auth system and this system? That sounds neat to me...

**Comment by blowdart** [comment]
@Eilon yup. Shall we have @HaoK pull it in officially then?

**Comment by Eilon** [comment]
I'm cool with that.

@GrabYourPitchforks any concerns about that? We'll add tests, of course.

**Comment by GrabYourPitchforks** [comment]
No real concerns, though there might be some edge cases that can trip you up. Consider the scenario where an application developer has customized the cookie name or the authentication type string. The sample package might assume these strings to be constant.

**Comment by Eilon** [comment]
Ah true true. We could presumably start out simple and handle the most common/default cases, and enhance based on customer feedback to support more highly customized scenarios.

**Comment by HaoK** [comment]
Dupe of https://github.com/aspnet/Security/issues/387
