### ISSUE TITLE
Extend KeyManagement to export key material

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/DataProtection#86]
The new data protector block is a pretty cool thing compared to what we used to have in ASP.NET *vPrevious* :trollface: 
Sadly, it (deliberately, according to @blowdart) lacks methods allowing to extract the material from a given key, which is really unfortunate.

Actually, I'd like to use the key management block in `AspNet.Security.OpenIdConnect.Server` to store/retrieve/export the keys used to sign access/identity tokens in a purely automated way. Having a new `Export` method on `IKey` would be truly helpful :smile:

I'm not sure asymmetric keys are currently supported (@blowdart told me they were), but having built-in support for RSA keys (`RSACryptoServiceProvider`) would be really cool. 

/cc @blowdart @GrabYourPitchforks @Eilon

**Comment by blowdart** [comment]
The inability to extract key material is by design and won't be changed.

**Comment by PinpointTownes** [comment]
It won't be changed until someone decides to change it :smile:

**Comment by blowdart** [comment]
Well, you can try to argue for it, but given the typical developer we're targeting this at allowing key extraction is a dangerous feature. We're trying to give folks an easy to use, make the right decisions for you solution just for ephemeral data.

Extending it for access or identity signing, where the format is outside of our control, for example JWT is beyond what data protection is aimed at.

**Comment by PinpointTownes** [comment]
Closing this ticket, as I finally implemented this feature in ASOS using a slightly different approach.
