### ISSUE TITLE
Allow KeyDerivation.Pbkdf2 to use a byte[] for the password

### ISSUE THREAD

**Issue by sqmgh** [aspnet/DataProtection#87]
Currently the function only allows passing a string to be hashed. It would be nice if you could pass a byte[] as well.

At the moment it seems kind of silly to be converting my byte[] to a string, so it can be converted back to a byte[]. Leaving a string floating around in GC land.

**Comment by muratg** [comment]
This sounds like a good idea.

**Comment by GrabYourPitchforks** [comment]
What's the scenario for this? Passwords are by definition textual input, thus their natural form is string rather than byte[].

**Comment by sqmgh** [comment]
The requests stems from dealing with SecureString, though it wouldn't surprise me if there was another use case for it.

In the past since Rfc2898DeriveBytes worked with both string and byte[]. As it's much more simple to marshal to a byte[] and zero it afterwards than trying to pin a string in memory and clear that, it was decided to use a byte[].

So I suppose it's an XY problem. In my case having support for SecureString would solve the problem. However, due to there being very minimal amount of support for it, older methods allowing byte[], the code converting to a byte[] internally, and that *someone* probably has another use case for it. I requested byte[] support.

**Comment by GrabYourPitchforks** [comment]
@sqmgh The SecureString API is essentially deprecated going forward and is slated for eventual removal from .NET Core. The general recommendation is that you switch to using simply String instead of SecureString throughout your application. Thus there's not really a huge benefit to providing a SecureString-based overload of this API.

See https://github.com/dotnet/apireviews/pull/8 for further discussion.

**Comment by bwolkerstorfer** [comment]
@GrabYourPitchforks @sqmgh 

It would actually make sense to have the possibility to use a byte[] for migration/extension of legacy application environments

Background:
I am maintaining an application that used to call Rfc2898DeriveBytes with the result from ``System.Text.Encoding.Unicode.GetBytes(password)`` - the new implementation uses ``System.Text.Encoding.UTF8.GetBytes(password)``. The plan is to switch all existing services to .NET Core and that would force all users (quite a lot) to get a new password if we want to get rid of Rfc2898DeriveBytes.

**Comment by blowdart** [comment]
As [Rfc2898DeriveBytes](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/Rfc2898DeriveBytes.cs) still exists in core why can you not continue with what you're doing?

**Comment by bwolkerstorfer** [comment]
The reason for switching is the fact, that KeyDerivation.Pbkdf2 can be extended to support best possible implementation for the operating system which would be beneficial in the future. But I will keep using Rfc2898DeriveBytes.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
