### ISSUE TITLE
SALT Generation

### ISSUE THREAD

**Issue by alexjusti** [aspnet/DataProtection#88]
The KeyDerivation takes a byte[] salt, but as of now I don't believe that there is a public method to generate a secure SALT value.  Am I missing something, or is this yet to be implemented?

**Comment by blowdart** [comment]
You're not missing anything, it's up to you to provide it, because you need to store it somewhere anyway.

**Comment by GrabYourPitchforks** [comment]
The easiest way to generate a salt is to use the RandomNumberGenerator class. Is the proposal for the KeyDerivation package to add a simple wrapper API that calls this on your behalf and returns a byte[]?

**Comment by mw2nukeboy** [comment]
Yes, that's what I'm looking for.

**Comment by blowdart** [comment]
How would you expect the salt to be returned to you? Hidden in the byte array? (At which point we're no longer following the public PBKDF2 spec)

**Comment by GrabYourPitchforks** [comment]
I interpreted this request as a separate API that just returns a random byte[], and that byte[] can then be fed in as the salt parameter to the PBKDF2 operation.

**Comment by blowdart** [comment]
@mw2nukeboy is a function to return a suitable salt what you want, or a way to just not pass one in at all?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2527
