### ISSUE TITLE
React to System.Security.Cryptography.* changes in CoreFX

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/DataProtection#90]
https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c

![image](https://cloud.githubusercontent.com/assets/6998306/9151283/543630a0-3dfd-11e5-9d66-d5b3e0d73dbd.png)

Related ticket: https://github.com/aspnet/Security/issues/396

**Comment by Tratcher** [comment]
https://github.com/aspnet/DataProtection/commit/9bebd183d78eb210ec2071ec4cc02458863bd0fd
